package view;

import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.WindowConstants;

/**
 * A popup frame that is used to print the symbols generated by pattern
 * generate.
 */
class PatternFrame extends javax.swing.JFrame {

  private static final long serialVersionUID = 1278472792511733197L;

  /**
   * Creates the frame which contains the symbols of the generated pattern. All init done here.
   */
  PatternFrame() {
    initComponents();
  }

  private void initComponents() {
    patternArea = new javax.swing.JTextArea();
    setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    setTitle("Pattern generated");
    JScrollPane patternPane = new javax.swing.JScrollPane();
    patternPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Pattern Symbols\n"));

    patternArea.setColumns(20);
    patternArea.setRows(5);
    patternPane.setViewportView(patternArea);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(patternPane, javax.swing.GroupLayout.PREFERRED_SIZE, 344,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(patternPane, javax.swing.GroupLayout.PREFERRED_SIZE, 304,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    pack();
  }

  private javax.swing.JTextArea patternArea;
  //private javax.swing.JScrollPane patternPane;

  /**
   * A getter for the text area where the pattern will be written.
   * 
   * @return The reference to the pattern area.
   */
  JTextArea getPatternArea() {
    return patternArea;
  }

}
